export const GET_TASK_API = "GET_TASK_API";

export const GET_TASK_API_PAGINATION = "GET_TASK_API_PAGINATION";

export const DEL_TASK_API = "DEL_TASK_API";

export const EDIT_TASK = 'EDIT_TASK';

export const DISPLAY_LOADING = 'DISPLAY_LOADING';

export const HIDE_LOADING = 'HIDE_LOADING';